"""GitHub REST API interactions: issues, labels, PRs, comments."""

from __future__ import annotations

from dataclasses import dataclass

import requests

from gertrudes.config import Config


@dataclass
class Issue:
    number: int
    title: str
    body: str


def _headers(config: Config) -> dict[str, str]:
    return {
        "Authorization": f"token {config.github_token}",
        "Accept": "application/vnd.github.v3+json",
    }


def _api(config: Config) -> str:
    return f"https://api.github.com/repos/{config.repo}"


def fetch_issues_by_label(config: Config, label: str) -> list[Issue]:
    """Fetch open issues with a given label."""
    resp = requests.get(
        f"{_api(config)}/issues",
        headers=_headers(config),
        params={"state": "open", "labels": label, "per_page": 100},
    )
    resp.raise_for_status()
    return [
        Issue(number=i["number"], title=i["title"], body=i.get("body") or "")
        for i in resp.json()
        if "pull_request" not in i  # skip PRs (GitHub returns them as issues)
    ]


def add_label(config: Config, issue_number: int, label: str):
    """Add a label to an issue, creating it first if it doesn't exist."""
    h = _headers(config)
    # Ensure label exists
    requests.post(
        f"{_api(config)}/labels",
        headers=h,
        json={"name": label, "color": "e4e669"},
    )
    requests.post(
        f"{_api(config)}/issues/{issue_number}/labels",
        headers=h,
        json={"labels": [label]},
    )


def remove_label(config: Config, issue_number: int, label: str):
    requests.delete(
        f"{_api(config)}/issues/{issue_number}/labels/{label}",
        headers=_headers(config),
    )


def comment_on_issue(config: Config, issue_number: int, body: str):
    requests.post(
        f"{_api(config)}/issues/{issue_number}/comments",
        headers=_headers(config),
        json={"body": body},
    )


def create_pull_request(
    config: Config,
    branch: str,
    issue_number: int,
    issue_title: str,
    summary: str,
    draft: bool = False,
) -> dict:
    """Create a PR and apply the configured label. Returns the PR JSON."""
    owner = config.repo.split("/")[0]
    h = _headers(config)

    body = f"""## Automated implementation

Generated by **gertrudes** in response to issue #{issue_number}.

### Changes

{summary}

---

Closes #{issue_number}
"""

    payload = {
        "title": f"Implement: {issue_title[:60]}",
        "body": body,
        "head": f"{owner}:{branch}",
        "base": config.base_branch,
        "draft": draft,
    }

    resp = requests.post(
        f"{_api(config)}/pulls",
        headers=h,
        json=payload,
    )
    if not resp.ok:
        raise RuntimeError(f"PR creation failed {resp.status_code}: {resp.json()}")
    pr = resp.json()

    # Apply label
    requests.post(
        f"{_api(config)}/issues/{pr['number']}/labels",
        headers=h,
        json={"labels": [config.pr_label]},
    )

    return pr
